// This is a placeholder service worker file.
// The actual service worker will be generated by vite-plugin-pwa.
// This file is here to ensure the directory structure is correct.

// If you need custom service worker logic, you can add it here.
// See https://vite-pwa-org.netlify.app/guide/service-worker.html for more information.

